[package]
name = "bevy-fluid-simulation"
version = "0.1.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.12.0"
rand = "0.8.5"
rayon = "1.8.0"
webbrowser = { version = "0.8", features = ["hardened"] }


[build-dependencies]
embed-resource = "2.4.0"

# Enable a small amount of optimization in debug mode
[profile.dev]
opt-level = 1

[profile.release]
opt-level = 3
strip = true
panic = 'abort'
lto = "thin"

[profile.profiling]
inherits = "release"
debug = true

# Enable high optimizations for dependencies (incl. Bevy), but not for our code:
[profile.dev.package."*"]
opt-level = 3

