[application]
name = "Bevy Fluid Simulation Blog"
default_platform = "web"
out_dir = "../docs"
base_path = "bevy-fluid-simulation"

[web.app]
title = "Bevy Fluid Simulation Blog"

[web.watcher]
[web.resource]
[web.resource.dev]