[application]
name = "Bevy Fluid Simulation Blog"
default_platform = "web"
out_dir = "../docs"


[web.app]
base_path = "bevy-fluid-simulation"
title = "BevyFluidSimulationBlog"

[web.watcher]
[web.resource]
[web.resource.dev]